### ISSUE TITLE
i2c_t3 multi-wire issue

### ISSUE THREAD

**Issue by d0ntrash** [nccgroup/TPMGenie#4]
It seems that the current i2c_t3 version is causing problems.

https://github.com/nox771/i2c_t3/issues/26
As you can see in this issue it is a known problem. If I got them right. 

Maybe you could mention this somewhere and/or provide a working version of the library.
If I can get it running, I will update this issue and specify the latest working version here.

**Comment by d0ntrash** [comment]
https://github.com/nox771/i2c_t3/commit/0a1b06111f9e16de20589a8c937fe7ef77089e99
This is probably the commit that leads to the problem. So any version before this should work for our purposes.

**Comment by jeremyncc** [comment]
Thanks for tracking this down. I haven't used TPM Genie in a while, so I hadn't realized that i2c_t3 had become broken. I should have mentioned the version of the module I used when doing the initial research. Sorry for any inconvenience.

**Comment by jeremyncc** [comment]
fixed in commit https://github.com/nccgroup/TPMGenie/commit/dd6dd2278dd3f49b25a15aaa1f15b6a737fb32b5
